### ISSUE TITLE
 Failed to load nodelet '/EstimatorNodelet` 

### ISSUE THREAD

**Issue by QQQ300kuai** [HITSZ-NRSL/Dynamic-VINS#10]
Excuse me, I tried to cut opencv3.4 and 4.3, but still got an error.

>  Failed to load nodelet '/EstimatorNodelet` of type `vins_estimator/EstimatorNodelet` to manager `nodelet_manager_pc'

![image](https://user-images.githubusercontent.com/55626566/200349444-4717803f-4e96-48b0-8a61-0cadf15cf561.png)

**Comment by YongshuaiZ** [comment]
请问你解决了吗，我也遇到了这个问题

**Comment by jianhengLiu** [comment]
参考 #1
