### ISSUE TITLE
运行TUM-RGBD数据时，RVIZ 接受 YOLO v5跟踪的数据报错

### ISSUE THREAD

**Issue by YongshuaiZ** [HITSZ-NRSL/Dynamic-VINS#14]
作者你好，可以单独运行Yolo_ros对图像进行跟踪吗。我看文件yolo_ros的话题是/untracked_info,但是我在rviz中可视化时，报错

**Comment by jianhengLiu** [comment]
可以的
yolo_ros应当没有输出可视化图片，而仅输出检测信息/untracked_info，rviz没有办法可视化

**Comment by YongshuaiZ** [comment]
好的谢谢作者

**Comment by yg-0527** [comment]
> 好的谢谢作者

你好，打扰你了，请问一下你TUM-RGBD数据集跑成功了吗？作者说的仅输出检测信息/untracked_info是在哪里可以看到呢？能解惑一下吗？
