### ISSUE TITLE
The main function of source code and the figure of OpenLORIS

### ISSUE THREAD

**Issue by HJMGARMIN** [HITSZ-NRSL/Dynamic-VINS#15]
Great work!
I met some problems when I read the paper and run it.
1. How do you draw the below picture of OpenLORIS? We also want to draw a similar figure to evaluate the robustness of our algorithm.
![image](https://user-images.githubusercontent.com/52454672/222618739-d1430bef-ff38-4736-a1d1-21147e8950eb.png)

2. Can you tell me where is the main function of the source code? I can not find the main() of estimator. Thank you very much.

**Comment by jianhengLiu** [comment]
1. To draw the figure, you could ref to the [openloris-scene-tools](https://github.com/lifelong-robotic-vision/openloris-scene-tools/tree/master/benchmark)
2. It's a multi-thread software, the main() is seperated to 2 main thread process. For tracker ref to [estimator_nodelet.cpp#L245](https://github.com/HITSZ-NRSL/Dynamic-VINS/blob/main/vins_estimator/src/estimator_nodelet.cpp#L245), for estimator ref to [estimator_nodelet.cpp#L245](https://github.com/HITSZ-NRSL/Dynamic-VINS/blob/main/vins_estimator/src/estimator_nodelet.cpp#L245)

**Comment by HJMGARMIN** [comment]
Thank you for your response.
I found that the process_tracker thread was started in "trackThread   = std::thread(&EstimatorNodelet::process_tracker, this);" of "void onInit() override". However, how the "onInit()" function works in the project? I do not know where is it called.

**Comment by jianhengLiu** [comment]
just ignore "onInit() override"



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 3, 2023 11:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HITSZ-NRSL/Dynamic-VINS] The main function of source code andthe figure of OpenLORIS (Issue #15)




 
Thank you for your response.
 I found that the process_tracker thread was started in "trackThread   = std::thread(&amp;EstimatorNodelet::process_tracker, this);" of "void onInit() override". However, how the "onInit()" function works in the project? I do not know where is it called.
