### ISSUE TITLE
undefined symbol: _ZN6Sophus3SO3C1Eddd

### ISSUE THREAD

**Issue by LYF-hahaha** [HITSZ-NRSL/Dynamic-VINS#17]
作者你好！

我在尝试按readme中的内容复现你的工作，目前遇到一个问题
在按如下指令运行cafe1-1数据集的时候出现报错undefined symbol: _ZN6Sophus3SO3C1Eddd（如下面截图）
看内容感觉与sophus有关，但sophus我也是按照git checkout a621ff 的要求安装的

希望能获得指点，感谢~

`roslaunch vins_estimator openloris_vio_pytorch.launch`
`roslaunch vins_estimator vins_rviz.launch`
`rosbag play ~/Dynamic_VINS/Dataset/OpenLORIS/cafe/cafe1-1.bag-imu.bag`

![image](https://user-images.githubusercontent.com/84720451/223315190-47baa322-310c-4457-bcf2-5fe1a67e3030.png)

**Comment by HJMGARMIN** [comment]
把OpenCV版本换成ROS自带的试试

**Comment by FanJinlong2023** [comment]
> 把OpenCV版本换成ROS自带的试试

换成ros的opencv后，还是出现错误

**Comment by FanJinlong2023** [comment]
![image](https://github.com/HITSZ-NRSL/Dynamic-VINS/assets/133203846/9b3a0b47-d93c-4b5f-b0b0-99df7cba61b2)
