### ISSUE TITLE
运行HITSZ & THUSZ Datasets出错

### ISSUE THREAD

**Issue by theyunfeng** [HITSZ-NRSL/Dynamic-VINS#22]
在跑hitsz_00.bag时，在运行roslaunch vins_estimator realsense_vio_campus.launch 的终端里出现
![image](https://user-images.githubusercontent.com/91672632/233052534-53d089f2-9975-4891-abda-9d14faa30673.png)，
在rviz中有warning
![image](https://user-images.githubusercontent.com/91672632/233052977-13c1a5f0-73d5-4be9-9d20-051a1ac3bb6b.png)
请问这是什么原因呢？

**Comment by jianhengLiu** [comment]
可能是opencv版本冲突？
默认是使用ubuntu 20.04，ROS noetic自带的opencv 4.2.0以及python3
确保编译和运行使用的是同一个python

**Comment by theyunfeng** [comment]
> 可能是opencv版本冲突？ 默认是使用ubuntu 20.04，ROS noetic自带的opencv 4.2.0以及python3 确保编译和运行使用的是同一个python

会是单独运行hitsz_00.bag的原因吗？

**Comment by jianhengLiu** [comment]
> > 可能是opencv版本冲突？ 默认是使用ubuntu 20.04，ROS noetic自带的opencv 4.2.0以及python3 确保编译和运行使用的是同一个python
> 
> 会是单独运行hitsz_00.bag的原因吗？

应该不是，只是把一个大数据分段了，数据应该没有影响

**Comment by theyunfeng** [comment]
ok,多谢，看样子是链接库版本不对，让cv_bridge强制链接自己的opencv就好了，虽然还是有warning

**Comment by zhixuan4123** [comment]
> 请问这个Upsample是怎么解决的尼？
