### ISSUE TITLE
运行openloris数据集没有semantic_mask

### ISSUE THREAD

**Issue by fishZeng** [HITSZ-NRSL/Dynamic-VINS#24]
使用的命令为：
`roslaunch vins_estimator openloris_vio_pytorch.launch`
`roslaunch vins_estimator vins_rviz.launch`
`rosbag play YOUR_PATH_TO_DATASET/market1-3.bag-imu.bag`
Rviz中使用image选定话题/vins_estimator/semantic_mask，没有图像输出

**Comment by jianhengLiu** [comment]
配置文件设置`show_track: 1`，图片发布在`/vins_estimator/semantic_mask`节点上

**Comment by ghost** [comment]
> 配置文件设置`show_track: 1`，图片发布在`/vins_estimator/semantic_mask`节点上

尝试了，能看到/vins_estimator/feature_img，但是没有视频中演示的检测框和mask图像，动态目标上的特征点显示为黄色边框

**Comment by ghost** [comment]
![2023-04-29 11-33-09屏幕截图](https://user-images.githubusercontent.com/128690427/235281915-e093063b-07d0-48c8-b291-a9850c43938b.png)
![2023-04-29 11-34-15屏幕截图](https://user-images.githubusercontent.com/128690427/235281918-4c2ae8db-8c4e-4002-b72a-4803151ae200.png)

我这边的版本是melodic，opencv版本为ros自带的3.2。今天用最新的代码重新编译了一遍且设置show_tarck为1，都是原始配置，显示的semantic_mask依旧是纯黑的图像。 @jianhengLiu
