### ISSUE TITLE
运行过程出错：unstable features tracking, please slowly move you device!

### ISSUE THREAD

**Issue by bzwwww** [HITSZ-NRSL/Dynamic-VINS#25]
按github中配置运行openloris和thusz数据集时都会报标题中的错误。
![image](https://user-images.githubusercontent.com/128358620/234810329-61b18d4f-344f-470d-a5d4-1f204316629f.png)
![image](https://user-images.githubusercontent.com/128358620/234810443-ff239f4c-6c81-46c2-b694-21b22a81b2c1.png)

**Comment by jianhengLiu** [comment]
可能是后端特征点估计飘了，可以分别尝试
1. 不使用静止初始化`static_init: 0`
2. 调大深度置信区间`depth_max_dist: 6`
3. 增大特征点数量`max_cnt: 130`

**Comment by bzwwww** [comment]
我采用的是config中原始配置，并且尝试将 depth_max_dist: 6 更改  和将最大特征点改到 250  都没有成功
并且我的rviz中没有正常的轨迹显示，我认为程序可能没有正常运行？

**Comment by jianhengLiu** [comment]
我这边用默认配置测试了一下好像都还正常
openloris: `roslaunch vins_estimator openloris_vio_pytorch.launch`
thusz: `roslaunch vins_estimator realsense_vio_campus.launch`

如果已经pull了最新版还是有问题的话，不清楚是不是这个commit(4e73b9e0806bbd094e7bedfadf4d5ebb402a27e4)可能版本有点差异？可以尝试改回来试试

**Comment by jianhengLiu** [comment]
我这边用默认配置测试了一下好像都还正常
openloris: `roslaunch vins_estimator openloris_vio_pytorch.launch`
thusz: `roslaunch vins_estimator realsense_vio_campus.launch`

如果已经pull了最新版还是有问题的话，不清楚是不是这个commit(4e73b9e0806bbd094e7bedfadf4d5ebb402a27e4)可能版本有点差异？可以尝试改回来试试

**Comment by bzwwww** [comment]
我之前运行的版本中是cv::SOLVEPNP_ITERATIVE，我重新clone了一下最新的版本，重新运行，还是会发现上述错误，但出现了不同的情况。
track_img中不再是深度图，同时我使用的不是ros-noetic中自带的OpenCV，我使用的版本是OpenCV4.5.5。您认为这两者中有关系吗？感谢您的帮助！
![image](https://user-images.githubusercontent.com/128358620/235081787-e797569b-9a0c-46b6-8fae-fb3cb08b1385.png)
![image](https://user-images.githubusercontent.com/128358620/235081820-f7a154c6-6377-4b3f-a814-fed98cac9e88.png)

**Comment by jianhengLiu** [comment]
有可能，我使用的是ros自带的opencv4.2.0
rviz显示不同可能是更改了topic，在display里重新选下应该就好



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月28日(周五) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HITSZ-NRSL/Dynamic-VINS] 运行过程出错：unstable features tracking, please slowly move you device! (Issue #25)




 
我之前运行的版本中是cv::SOLVEPNP_ITERATIVE，我重新clone了一下最新的版本，重新运行，还是会发现上述错误，但出现了不同的情况。
 track_img中不再是深度图，同时我使用的不是ros-noetic中自带的OpenCV，我使用的版本是OpenCV4.5.5。您认为这两者中有关系吗？感谢您的帮助！

**Comment by bzwwww** [comment]
我重新编译了OpenCV4.2.0的版本，已经可以成功运行，感谢您的帮助！

**Comment by yg-0527** [comment]
你好，请问这个一直下载不了源码是怎么回事啊？我网络良好，也试过开vpn，都显示网页404。请问谁可以分享一下源码吗？万分感谢！！！！

**Comment by bzwwww** [comment]
你好，还想问一下这份代码里还有闭环检测的功能吗，我拿这套代码跑kitti数据集时出现了比较大的偏差，想尝试开闭环之后试试。我在yaml文件中更改了下面的配置，但没有起作用。
loop_closure: 1                    # start loop closure
fast_relocalization: 1             # useful in real-time and large project

**Comment by jianhengLiu** [comment]
应该是launch文件中注释了回环的节点，有需要的话，取消注释应该就能用
