### ISSUE TITLE
Nothing appears in rviz

### ISSUE THREAD

**Issue by QQQ300kuai** [HITSZ-NRSL/Dynamic-VINS#3]
![image](https://user-images.githubusercontent.com/55626566/191411026-a1b5220b-65ab-4996-9c5c-7cba60ab9396.png)
line 3 `rosbag play YOUR_PATH_TO_DATASET/cafe.bag ` ，
i would like to know the path of cafe.bag,is cafe1-1.bag?or cafe1-2.bag?
thanks

**Comment by jianhengLiu** [comment]
It's cafe1-1.bag or cafe1-2.
Sorry for unclear instruction.

**Comment by QQQ300kuai** [comment]
![image](https://user-images.githubusercontent.com/55626566/191412421-c43a0c90-e11a-4205-a668-89993580fa71.png)

Excuse me.
My problem is that I follow the instruction documentation but the trajectory is not displayed in rviz and there is no segmentation map.
`python YOUR_PATH_TO_DYNAMIC_VINS/scripts/merge_imu_topics.py cafe1-1.bag cafe1-2.bag`
`roslaunch vins_estimator openloris_vio_pytorch.launch`
`roslaunch vins_estimator vins_rviz.launch # Visualization`
`rosbag play YOUR_PATH_TO_DATASET/cafe.bag `

**Comment by jianhengLiu** [comment]
I commented the yolo_ros relevant launch (line 5-7) in the openloris_vio_pytorch.launch.
Cancel the comment should be work.

**Comment by jianhengLiu** [comment]
> It's cafe1-1.bag or cafe1-2. Sorry for unclear instruction.

apology,  should be cafe1-1-imu.bag with merge imu topics

**Comment by QQQ300kuai** [comment]
I think there is a problem with the dataset in 3.1, I re-merge the gyro and accel topics into one.When re-executing the following command, it has been running for more than 10 minutes and has not stopped.Is this normal？
  `python YOUR_PATH_TO_DYNAMIC_VINS/scripts/merge_imu_topics.py cafe1-1.bag cafe1-2.bag`
![image](https://user-images.githubusercontent.com/55626566/191444145-ce3f48b8-6502-472a-8461-c6530aa42e10.png)

**Comment by jianhengLiu** [comment]
it seems normal.
perhaps printing out messages makes it slow, might try comment relevant 'print' code in the python file
