### ISSUE TITLE
Rviz 显示报错

### ISSUE THREAD

**Issue by yg-0527** [HITSZ-NRSL/Dynamic-VINS#31]
作者你好，我按文档配置运行：
roslaunch vins_estimator openloris_vio_pytorch.launch
roslaunch vins_estimator vins_rviz.launch
rosbag play /home/yugui/code/catkin_ws/datas/cafe1-2.bag-imu.bag
之后，rviz中的Odometry中出现Status：Error错误，请问是什么原因？需要怎么去解决？

![微信图片_20230806145709](https://github.com/HITSZ-NRSL/Dynamic-VINS/assets/102644325/5110ed16-f7e1-475a-8881-0ab033f74d21)

**Comment by lizhi00701** [comment]
请问这个问题您解决了吗？

**Comment by yg-0527** [comment]
好像把那个话题改成可以接收的话题就行了


Sl&nbsp;eeping
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HITSZ-NRSL/Dynamic-VINS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月20日(星期三) 下午4:14
***@***.***&gt;;
抄送:&nbsp;"Sl ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [HITSZ-NRSL/Dynamic-VINS] Rviz 显示报错 (Issue #31)





 
请问这个问题您解决了吗？
