### ISSUE TITLE
HITSZ和THUSZ数据集下载

### ISSUE THREAD

**Issue by DrZ-21** [HITSZ-NRSL/Dynamic-VINS#32]
您好，
我按照您提供的数据集下载连接点进去是这个：
![2023-08-07 15-13-54屏幕截图](https://github.com/HITSZ-NRSL/Dynamic-VINS/assets/74588810/bf4c3c82-fb02-4d23-9436-1cf2c702adff)
然后点击hitsz00.bag弹出了另一个页面：
![2023-08-07 15-13-33屏幕截图](https://github.com/HITSZ-NRSL/Dynamic-VINS/assets/74588810/833de7e2-b81f-4929-bfdf-ea8ba327a5b4)
但是bag并没有下载下来，请问我应该怎样操作把这些包全都下载下来呢？

**Comment by jianhengLiu** [comment]
可以尝试更换浏览器进行下载（Chrome，Edge）
或者可以参考https://github.com/HITSZ-NRSL/Dynamic-VINS/blob/main/scripts/download_hitsz.sh ，替换其中的链接，使用脚本下载

**Comment by DrZ-21** [comment]
好的，感谢
