### ISSUE TITLE
imu in disorder

### ISSUE THREAD

**Issue by zhixuan4123** [HITSZ-NRSL/Dynamic-VINS#34]
您好，OpenLORIS 数据按照scripts/merge_imu_topics.py合并imu数据后，运行会出现：imu message in disorder.是什么原因尼？

**Comment by yuxingyun** [comment]
你好，可以添加下微信交流一下吗？我最近也在研究这个项目。微信号:YXY15381409392

**Comment by yg-0527** [comment]
> 你好，可以添加下微信交流一下吗？我最近也在研究这个项目。微信号：YXY15381409392

你好，你的微信加不上了，我最近也在研究这个项目，能交流一下吗。微信号：18870320355
