### ISSUE TITLE
Can you provide me with detailed materials about the added IMU-aided feature tracking?

### ISSUE THREAD

**Issue by Eunseong17** [HITSZ-NRSL/Dynamic-VINS#37]
Thank you for your great work. 
I am wondering about IMU-aided feature tracking. I searched for this reference in your paper (Dynamic-VINS), but I couldn't find it.

**Comment by jianhengLiu** [comment]
Assume that the motion between two image frames is pure rotation R^k_{k+1}
![image](https://github.com/HITSZ-NRSL/Dynamic-VINS/assets/41661134/615a472b-f0ee-4718-a22f-8a6475eaf989)
w_k is the frame angular velocity measured by the gyroscope
![image](https://github.com/HITSZ-NRSL/Dynamic-VINS/assets/41661134/6e4ed4e1-f58a-4254-aa5d-480cf9fbc902)
K is the intrinsic matrix, p_k is the pixel coordinate

**Comment by Eunseong17** [comment]
Thank you for the response.

**Comment by Eunseong17** [comment]
I have additional question.
It appears that the equations only account for rotation. Is translation (straight-line motion) not considered in this model?

Thank you.
