### ISSUE TITLE
ground truth of HITSZ & THUSZ Datasets

### ISSUE THREAD

**Issue by Mahmoudadham4040** [HITSZ-NRSL/Dynamic-VINS#39]
could you please provide us with the ground truth or the RTK-GPS trajectories -if any- for the  HITSZ & THUSZ Datasets ?

**Comment by jianhengLiu** [comment]
Sorry that these datasets do not contain GT or GPS trajectory.
It is collected for qualitative experiments, and you could compare results with loop-closure trajectory or satellite map.

**Comment by Mahmoudadham4040** [comment]
Thanks for your consideration.
I have another point, I don't have depth image messages and want to evaluate Vins with yolo? could you please provide me your suggestions to edit in this code?

**Comment by jianhengLiu** [comment]
One plausible way is to modify codes to add choice to receive datastream without depth, and mask all features in yolo bbox



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 14, 2023 19:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HITSZ-NRSL/Dynamic-VINS] ground truth of HITSZ &amp; THUSZ Datasets(Issue #39)




 
Thanks for your consideration.
 I have another point, I don't have depth image messages and want to evaluate Vins with yolo? could you please provide me your suggestions to edit in this code?
