### ISSUE TITLE
运行cafe1-1.bag-imu.bag包时卡顿

### ISSUE THREAD

**Issue by Rosa712** [HITSZ-NRSL/Dynamic-VINS#40]
![image](https://github.com/HITSZ-NRSL/Dynamic-VINS/assets/115403971/77aeed6e-04d6-47f5-9960-a9fe70652592)
按照readme解压得到cafe1-1.bag并运行merge_imu_topics.py得到cafe1-1.bag-imu.bag，单独运行bag不卡顿，但是运行roslaunch vins_estimator openloris_vio_pytorch.launch后在运行bag直接卡住

**Comment by jianhengLiu** [comment]
可能因为bag没有解压（decompress），导致需要同时解压同时跑程序，导致处理缓慢
