### ISSUE TITLE
roslaunch vins_estimator openloris_vio_pytorch.launch 刚运行报错[demo_server-1] process has died 

### ISSUE THREAD

**Issue by Alex20000206** [HITSZ-NRSL/Dynamic-VINS#42]
![2023-11-17 11-48-55屏幕截图](https://github.com/HITSZ-NRSL/Dynamic-VINS/assets/151111190/b70964ea-40c5-4592-a84d-7c97641cab5c)
请问一下，在刚运行命令roslaunch vins_estimator openloris_vio_pytorch.launch的时候，就出现了如上报错，这是什么情况呢？

**Comment by ericlai0323** [comment]
```
pip3 install numpy==1.23.5
```
Use this command can solve this problem, because the higher version of numpy is not support 'np.float'.
