### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by QQQ300kuai** [HITSZ-NRSL/Dynamic-VINS#5]
When I run `roslaunch vins_estimator openloris_vio_pytorch.launch`, I encounter the following error：
![image](https://user-images.githubusercontent.com/55626566/195662263-20a6f9f4-80a4-408d-a56f-ff37df825d15.png)
Can you tell me how I should handle this.

**Comment by jianhengLiu** [comment]
Check if you mistakenly change `#!/usr/bin/env python3` in `youlo_ros/src/demo_service_server.py`

**Comment by QQQ300kuai** [comment]
I checked. Nothing changed.

**Comment by jianhengLiu** [comment]
It seems like a python path problem.
You could try using conda to create a new environment to avoid this problem?

**Comment by QQQ300kuai** [comment]
Again after installation, another error: `Cannot locate node of type yolo_trt_ros.py`
![image](https://user-images.githubusercontent.com/55626566/195821391-2de8d183-e339-461f-aa75-6dd5dca73cc2.png)

**Comment by jianhengLiu** [comment]
It seems that you run [openloris_vio_tensorrt.launch](https://github.com/HITSZ-NRSL/Dynamic-VINS/blob/main/vins_estimator/launch/openloris/openloris_vio_tensorrt.launch) which requires tensorrt version of yolo_ros (`tensorrt branch`).
Please run [openloris_vio_pytorch.launch](https://github.com/HITSZ-NRSL/Dynamic-VINS/blob/main/vins_estimator/launch/openloris/openloris_vio_pytorch.launch).

**Comment by QQQ300kuai** [comment]
I use conda to create a new environment,but the problem still exists.
> Again after installation, another error: `Cannot locate node of type yolo_trt_ros.py` ![image](https://user-images.githubusercontent.com/55626566/195821391-2de8d183-e339-461f-aa75-6dd5dca73cc2.png)

**Comment by QQQ300kuai** [comment]
I found the problem.
`#!/usr/bin/env python`   In ubuntu it becomes `#!/usr/bin/env python\r`
The solution:
`Vi` the file
Input `:set ff = unix`
Enter `:wq` to save the changes
Thank you!
