### ISSUE TITLE
yolo频率问题

### ISSUE THREAD

**Issue by HeadReaper-hc** [HITSZ-NRSL/Dynamic-VINS#50]
你好，我单独运行yolo_ros可以实现30Hz发布/untracked_info, 但是同时运行vins只能实现10Hz发布/untracked_info，请问你知道这是什么原因吗？

测试环境是是I7和2080显卡，使用的是pytorch版yolo

**Comment by jianhengLiu** [comment]
不清楚哎，理论上二者是独立模块，应该不会相互影响



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月1日(周五) 中午11:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HITSZ-NRSL/Dynamic-VINS] yolo频率问题 (Issue #50)




 
你好，我单独运行yolo_ros可以实现30Hz发布/untracked_info, 但是同时运行vins只能实现10Hz发布/untracked_info，请问你知道这是什么原因吗？
 
测试环境是是I7和2080显卡，使用的是pytorch版yolo

**Comment by HeadReaper-hc** [comment]
@jianhengLiu 谢谢回复。我想问一下你在jetson xavier上测的时候开启yolo和vins能30Hz实时运行吗

**Comment by jianhengLiu** [comment]
印象中，agx上跑yolo大约在20hz左右，vins是可以实时的
