### ISSUE TITLE
VO mode BUG🐛

### ISSUE THREAD

**Issue by theyunfeng** [HITSZ-NRSL/Dynamic-VINS#52]
VO模式下在特征点很少的时候后端会报错  /usr/include/eigen3/Eigen/src/Core/Redux.h:413: typename Eigen::internal::traits<T>::Scalar Eigen::DenseBase<Derived>::redux(const Func&) const [with BinaryOp = Eigen::internal::scalar_max_op<double, double>; Derived = Eigen::CwiseUnaryOp<Eigen::internal::scalar_abs_op<double>, const Eigen::Matrix<double, -1, -1> >; typename Eigen::internal::traits<T>::Scalar = double]: Assertion `this->rows()>0 && this->cols()>0 && "you are using an empty matrix"' failed.  经过调试发现问题在当marginalization_flag == MARGIN_OLD时，代码在下图位置marginalize() 函数中崩溃，且感觉VO模式貌似不是很准，请问是参数问题吗？
![image](https://github.com/HITSZ-NRSL/Dynamic-VINS/assets/91672632/2897bc78-e836-44fb-88d6-0efb3ecfeb14)

**Comment by jianhengLiu** [comment]
因为VO模式是在VINS上简单的把Inertial相关的去掉，所以确实不是很稳定，ORBSLAM之类的会对VO有更细致的考量
