### ISSUE TITLE
imu标定方法

### ISSUE THREAD

**Issue by theyunfeng** [HITSZ-NRSL/Dynamic-VINS#53]
请问您imu内参是用什么标定的？我用imu_utils标定realsense的内参和您给的差几个数量级，如下图，而且用您给的imu内参在相机有较大晃动时还是正常的，用imu_utils标出来的内参在相机有较大晃动时，轨迹直接就漂了，此时相机不动算法计算的轨迹也一直在漂
![image](https://github.com/HITSZ-NRSL/Dynamic-VINS/assets/91672632/0bcefbd8-608c-4f4e-9eea-aa130ef25f29)

**Comment by jianhengLiu** [comment]
我以前也是用imu_utils来标定imu的，不过因为这些bias实际一直都是会变的，所以一次标定并不能一劳永逸。
因此imu内参的bias给了一个更大的值，来表明imu不确定度更大点，更多的使用视觉特征来进行定位
