### ISSUE TITLE
yolo_ros和dynamic_vins的时间戳同步问题

### ISSUE THREAD

**Issue by XU0510** [HITSZ-NRSL/Dynamic-VINS#55]
您好，我在学习您的代码的时候有如下的疑问，yolo_ros和dynamic_vins是并行运行，如果同时订阅同一个图像信息，但是由于处理时间的差异如何保证，yolo_ros的输出publish的yolo结果和我dynamic_vins的视觉处理的是同一张图像呢？感谢指导

**Comment by jianhengLiu** [comment]
通过时间戳来同步



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月23日(周二) 晚上6:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HITSZ-NRSL/Dynamic-VINS] yolo_ros和dynamic_vins的时间戳同步问题 (Issue #55)




 
您好，我在学习您的代码的时候有如下的疑问，yolo_ros和dynamic_vins是并行运行，如果同时订阅同一个图像信息，但是由于处理时间的差异如何保证，yolo_ros的输出publish的yolo结果和我dynamic_vins的视觉处理的是同一张图像呢？感谢指导

**Comment by XU0510** [comment]
感谢大佬指导！我仔细看了一下代码理解时间戳的问题了，但是我在运行别的数据集的时候遇到了图像格式的问题，我只能运行sensor_msgs/Image         [060021388200f6f0f447d0fcd9c64743]类型的图像数据，请问这个有接口可以修改吗？

**Comment by XU0510** [comment]
> 感谢大佬指导！我仔细看了一下代码理解时间戳的问题了，但是我在运行别的数据集的时候遇到了图像格式的问题，我只能运行sensor_msgs/Image [060021388200f6f0f447d0fcd9c64743]类型的图像数据，请问这个有接口可以修改吗？

已经解决，将话题的类型修改即可
