### ISSUE TITLE
Result of Different Playing Rate

### ISSUE THREAD

**Issue by Kyle-Xu001** [HITSZ-NRSL/Dynamic-VINS#8]
Hi, I tried to use the recorded rosbag to test this algorithm. The results are different when playing the rosbag with different playing rates. With a normal playing rate X 1.0, it has large drifts and often slows down or suddenly accelerates at some frames, especially when it detects more features. When playing rate X 0.2, the drift is quite small. What do you think of this problem?

**Comment by jianhengLiu** [comment]
It might result from the data loss. I used to transfer image data from nuc to atlas, while the bandwidth is limited, which makes some image frames loss and lead to bad results.

**Comment by Kyle-Xu001** [comment]
Thank you for your help.
